workspace = { members = [ "crates/input_derive", "crates/macros","crates/map_parser", "crates/randomgen"] }
[package]
name = "quaker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

[dependencies]        
bevy = { version = "0.13.*", features = ["bevy_gltf"] }#, features = ["dynamic_linking"]
map_parser = { path = "crates/map_parser" }
macros = { path = "crates/macros" }
input_derive = { path = "crates/input_derive" }
bevy_rapier3d = { version = "0.25.0", features = ["parallel","debug-render-3d","simd-stable"] }
serde = "1.0.197"
serde_json = "1.0.114"
bevy_obj = { version = "0.13.0" } #, features = ["scene"] 
bevy_kira_audio = "0.19.0"
bevy-inspector-egui = "0.23.4"
bevy-scene-hook = "10.0.0"
bevy_simple_text_input = "0.5.1"

# Enable max optimizations for dependencies, but not for our code:
[profile.dev.package."*"]
opt-level = 3
