workspace = { members = [ "crates/macros","crates/map_parser"] }
[package]
name = "quaker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

[dependencies]        
bevy = { version = "0.13.*"  }#, features = ["dynamic_linking"]
map_parser = { path = "crates/map_parser" }
macros = { path = "crates/macros" }
bevy_rapier3d = { version = "0.25.0", features = ["parallel","debug-render-3d","simd-stable"] }
serde = "1.0.197"
serde_json = "1.0.114"
bevy_obj = { version = "0.13.0" } #, features = ["scene"] 

# Enable max optimizations for dependencies, but not for our code:
[profile.dev.package."*"]
opt-level = 3
