workspace = { members = ["crates/map_parser"] }
[package]
name = "quaker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

[dependencies]        
map_parser = { path = "crates/map_parser" }