workspace = { members = [ "crates/macros","crates/map_parser"] }
[package]
name = "quaker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

[dependencies]        
bevy = { version = "0.13.*", features = ["dynamic_linking"] }
map_parser = { path = "crates/map_parser" }
macros = { path = "crates/macros" }
implicit3d = "0.14.2"
nalgebra = "0.22.1"
