[package]
name = "qwak_helper_types"
version = "0.1.0"
edition = "2024"

[dependencies]
serde      = { workspace = true }
extism-pdk = { workspace = true }

[lib]
path = "lib.rs"

[lints]
workspace = true