use faststr::FastStr;
use qwak_helper_types::{Attack, SoundEffect, WeaponAnimations, WeaponData};
use std::collections::HashMap;

pub fn get_weapons() -> HashMap<FastStr, WeaponData> {
    [
        ("weapon_nukegun".into(), WeaponData {
            shoot_sfx: SoundEffect::Single("sounds/Player/Guns/NukeGun/Launch.ogg".into()),
            id: "weapon_nukegun".into(),
            slot: 9,
            texture_file: "textures/weapons/WeaponMegaTexture.png".into(),
            model_file: "models/Player/First Person/NukeGun.glb".into(),
            scale: 0.01,
            animations: WeaponAnimations {
                idle: 0,
                shoot1: 5,
                shoot2: 6,
                reload: Some(4),
                fire_time1: 0.625,
                anim_time1: 0.625,
                fire_time2: 0.625,
                anim_time2: 0.625,
                reload_time_skip: 2.26,
                reload_time: 2.26,
            },
            offset: [0.1, -1.5, 0.0],
            rotation: [-5.0, 180.0, 0.0],
            pickup_sound: None,
            attack1: Attack::Projectile {
                projectile: "nuke".into(),
            },
            attack2: Attack::Projectile {
                projectile: "nuke".into(),
            },
            pickup_message1: "PICKED UP: ".into(),
            pickup_message2: "! FOR INDOOR USAGE ONLY!".into(),
            fancy_name: "sun slinger".into(),
        }),
        ("weapon_revolver".into(), WeaponData {
            shoot_sfx: SoundEffect::Single("sounds/Player/Guns/Revolver/Shoot.ogg".into()),
            id: "weapon_revolver".into(),
            slot: 1,
            texture_file: "textures/weapons/WeaponMegaTexture.png".into(),
            model_file: "models/Player/First Person/Revolver.glb".into(),
            scale: 0.01,
            animations: WeaponAnimations {
                idle: 0,
                shoot1: 5,
                shoot2: 5,
                reload: None,
                fire_time1: 0.625,
                anim_time1: 0.625,
                fire_time2: 0.625,
                anim_time2: 0.625,
                reload_time_skip: 1.0,
                reload_time: 1.0,
            },
            offset: [0.1, -1.5, 0.0],
            rotation: [-5.0, 180.0, 0.0],
            pickup_sound: None,
            attack1: Attack::RayCast {
                amount: 1,
                angle_mod: 2.0,
                damage: 27.0,
                damage_mod: 5.0,
                range: 100.0,
            },
            attack2: Attack::RayCast {
                amount: 1,
                angle_mod: 2.0,
                damage: 27.0,
                damage_mod: 5.0,
                range: 100.0,
            },
            pickup_message1: "PICKED UP: ".into(),
            pickup_message2: "!".into(),
            fancy_name: "revolver".into(),
        }),
        ("weapon_pumpshotgun".into(), WeaponData {
            shoot_sfx: SoundEffect::Single("sounds/Player/Guns/PumpShotgun/Shoot.ogg".into()),
            id: "weapon_pumpshotgun".into(),
            slot: 2,
            texture_file: "textures/weapons/WeaponMegaTexture.png".into(),
            model_file: "models/Player/First Person/PumpShotgun.glb".into(),
            scale: 0.01,
            animations: WeaponAnimations {
                idle: 0,
                shoot1: 5,
                shoot2: 5,
                reload: None,
                fire_time1: 1.45,
                anim_time1: 1.55,
                fire_time2: 1.45,
                anim_time2: 1.55,
                reload_time_skip: 1.0,
                reload_time: 1.0,
            },
            offset: [0.1, -1.5, 0.0],
            rotation: [-5.0, 180.0, 0.0],
            pickup_sound: None,
            attack1: Attack::RayCast {
                amount: 6,
                angle_mod: 5.0,
                damage: 13.0,
                damage_mod: 5.0,
                range: 100.0,
            },
            attack2: Attack::RayCast {
                amount: 6,
                angle_mod: 5.0,
                damage: 13.0,
                damage_mod: 5.0,
                range: 100.0,
            },
            pickup_message1: "PICKED UP: ".into(),
            pickup_message2: "!".into(),
            fancy_name: "pump shotgun".into(),
        }),
        ("weapon_dynamite".into(), WeaponData {
            shoot_sfx: SoundEffect::Single("sounds/Player/Guns/Dynamite/Throw.ogg".into()),
            id: "weapon_dynamite".into(),
            slot: 5,
            texture_file: "textures/weapons/WeaponMegaTexture.png".into(),
            model_file: "models/Player/First Person/Dynamite.glb".into(),
            scale: 0.01,
            animations: WeaponAnimations {
                idle: 0,
                shoot1: 5,
                shoot2: 5,
                reload: None,
                fire_time1: 1.2,
                anim_time1: 1.292,
                fire_time2: 1.2,
                anim_time2: 1.292,
                reload_time_skip: 1.0,
                reload_time: 1.0,
            },
            offset: [0.0, -1.5, 0.0],
            rotation: [-5.0, 180.0, 0.0],
            pickup_sound: None,
            attack1: Attack::None,
            attack2: Attack::None,
            pickup_message1: "PICKED UP: ".into(),
            pickup_message2: "! SEEMS LIKE A BAD IDEA...".into(),
            fancy_name: "bundle o' dynamite".into(),
        }),
        ("weapon_flamethrower".into(), WeaponData {
            shoot_sfx: SoundEffect::Single("sounds/Player/Guns/Flamethrower/fire.ogg".into()),
            id: "weapon_flamethrower".into(),
            slot: 7,
            texture_file: "textures/weapons/WeaponMegaTexture.png".into(),
            model_file: "models/Player/First Person/Flamethrower.glb".into(),
            scale: 0.01,
            animations: WeaponAnimations {
                idle: 0,
                shoot1: 0,
                shoot2: 0,
                reload: None,
                fire_time1: 0.1,
                anim_time1: 2.625,
                fire_time2: 0.1,
                anim_time2: 2.625,
                reload_time_skip: 1.0,
                reload_time: 1.0,
            },
            offset: [0.1, -1.5, 0.0],
            rotation: [-5.0, 180.0, 0.0],
            pickup_sound: None,
            attack1: Attack::None,
            attack2: Attack::None,
            pickup_message1: "PICKED UP: ".into(),
            pickup_message2: "! KEEP AWAY FROM TUPPERWARE!".into(),
            fancy_name: "flamethrower".into(),
        }),
        ("weapon_smgbelter".into(), WeaponData {
            shoot_sfx: SoundEffect::Single("sounds/Player/Guns/SmgBelter/Shoot.ogg".into()),
            id: "weapon_smgbelter".into(),
            slot: 3,
            texture_file: "textures/weapons/WeaponMegaTexture.png".into(),
            model_file: "models/Player/First Person/SmgBelter.glb".into(),
            scale: 0.01,
            animations: WeaponAnimations {
                idle: 0,
                shoot1: 5,
                shoot2: 5,
                reload: None,
                fire_time1: 0.1,
                anim_time1: 0.25,
                fire_time2: 0.1,
                anim_time2: 0.25,
                reload_time_skip: 1.0,
                reload_time: 1.0,
            },
            offset: [0.1, -1.5, 0.0],
            rotation: [-5.0, 180.0, 0.0],
            pickup_sound: None,
            attack1: Attack::RayCast {
                amount: 1,
                angle_mod: 7.0,
                damage: 7.0,
                damage_mod: 2.0,
                range: 100.0,
            },
            attack2: Attack::RayCast {
                amount: 1,
                angle_mod: 7.0,
                damage: 7.0,
                damage_mod: 2.0,
                range: 100.0,
            },
            pickup_message1: "PICKED UP: ".into(),
            pickup_message2: "! PEW PEW!".into(),
            fancy_name: "belter".into(),
        }),
        ("weapon_supercoolgun".into(), WeaponData {
            shoot_sfx: SoundEffect::Single("sounds/Player/Guns/Scg/Shoot.ogg".into()),
            id: "weapon_supercoolgun".into(),
            slot: 8,
            texture_file: "textures/weapons/WeaponMegaTexture.png".into(),
            model_file: "models/Player/First Person/SuperCoolGun.glb".into(),
            scale: 0.01,
            animations: WeaponAnimations {
                idle: 0,
                shoot1: 5,
                shoot2: 6,
                reload: None,
                fire_time1: 0.8,
                anim_time1: 0.985,
                fire_time2: 0.458,
                anim_time2: 0.458,
                reload_time_skip: 1.0,
                reload_time: 1.0,
            },
            offset: [0.1, -1.5, 0.0],
            rotation: [-5.0, 180.0, 0.0],
            pickup_sound: None,
            attack1: Attack::None,
            attack2: Attack::None,
            pickup_message1: "PICKED UP: ".into(),
            pickup_message2: "!".into(),
            fancy_name: "UNNAMNED_WEAPON".into(),
        }),
        ("weapon_bayonet".into(), WeaponData {
            shoot_sfx: SoundEffect::Random(vec![
                "sounds/Player/Guns/Bayonet/swish-1.ogg".into(),
                "sounds/Player/Guns/Bayonet/swish-10.ogg".into(),
                "sounds/Player/Guns/Bayonet/swish-11.ogg".into(),
                "sounds/Player/Guns/Bayonet/swish-12.ogg".into(),
                "sounds/Player/Guns/Bayonet/swish-13.ogg".into(),
                "sounds/Player/Guns/Bayonet/swish-2.ogg".into(),
                "sounds/Player/Guns/Bayonet/swish-3.ogg".into(),
                "sounds/Player/Guns/Bayonet/swish-4.ogg".into(),
                "sounds/Player/Guns/Bayonet/swish-5.ogg".into(),
                "sounds/Player/Guns/Bayonet/swish-6.ogg".into(),
                "sounds/Player/Guns/Bayonet/swish-7.ogg".into(),
                "sounds/Player/Guns/Bayonet/swish-8.ogg".into(),
                "sounds/Player/Guns/Bayonet/swish-9.ogg".into(),
            ]),
            id: "weapon_bayonet".into(),
            slot: 0,
            texture_file: "textures/weapons/WeaponMegaTexture.png".into(),
            model_file: "models/Player/First Person/Bayonet.glb".into(),
            scale: 0.01,
            animations: WeaponAnimations {
                idle: 1,
                shoot1: 5,
                shoot2: 6,
                reload: None,
                fire_time1: 0.4,
                anim_time1: 0.625,
                fire_time2: 0.4,
                anim_time2: 0.625,
                reload_time_skip: 1.0,
                reload_time: 1.0,
            },
            offset: [0.0, -1.5, 0.0],
            rotation: [-5.0, 180.0, 0.0],
            pickup_sound: None,
            attack1: Attack::RayCast {
                amount: 1,
                angle_mod: 0.0,
                damage: 10.0,
                damage_mod: 1.0,
                range: 1.3,
            },
            attack2: Attack::RayCast {
                amount: 1,
                angle_mod: 0.0,
                damage: 5.0,
                damage_mod: 2.0,
                range: 1.3,
            },
            pickup_message1: "PICKED UP: ".into(),
            pickup_message2: "! SLICE AND DICE!".into(),
            fancy_name: "bayonet".into(),
        }),
        ("weapon_supershotgun".into(), WeaponData {
            shoot_sfx: SoundEffect::Single(
                "sounds/Player/Guns/SuperShotgun/shotgunShot.ogg".into(),
            ),
            id: "weapon_supershotgun".into(),
            slot: 6,
            texture_file: "textures/weapons/WeaponMegaTexture.png".into(),
            model_file: "models/Player/First Person/SuperShotgun.glb".into(),
            scale: 0.01,
            animations: WeaponAnimations {
                idle: 1,
                shoot1: 5,
                shoot2: 5,
                reload: Some(4),
                fire_time1: 0.4,
                anim_time1: 0.4,
                fire_time2: 0.4,
                anim_time2: 0.4,
                reload_time_skip: 1.3,
                reload_time: 1.542,
            },
            offset: [0.1, -1.5, 0.0],
            rotation: [-5.0, 180.0, 0.0],
            pickup_sound: None,
            attack1: Attack::RayCast {
                amount: 12,
                angle_mod: 8.0,
                damage: 13.0,
                damage_mod: 5.0,
                range: 100.0,
            },
            attack2: Attack::RayCast {
                amount: 12,
                angle_mod: 8.0,
                damage: 13.0,
                damage_mod: 5.0,
                range: 100.0,
            },
            pickup_message1: "PICKED UP: ".into(),
            pickup_message2: "! GROOVY!".into(),
            fancy_name: "super shotgun".into(),
        }),
        ("weapon_rpg".into(), WeaponData {
            shoot_sfx: SoundEffect::Single("sounds/Player/Guns/Rpg/rocket_launch.ogg".into()),
            id: "weapon_rpg".into(),
            slot: 4,
            texture_file: "textures/weapons/WeaponMegaTexture.png".into(),
            model_file: "models/Player/First Person/RPG.glb".into(),
            scale: 0.01,
            animations: WeaponAnimations {
                idle: 0,
                shoot1: 6,
                shoot2: 6,
                reload: None,
                fire_time1: 0.5,
                anim_time1: 0.625,
                fire_time2: 0.5,
                anim_time2: 0.625,
                reload_time_skip: 1.0,
                reload_time: 1.0,
            },
            offset: [0.1, -1.5, 0.0],
            rotation: [-5.0, 180.0, 0.0],
            pickup_sound: None,
            attack1: Attack::Projectile {
                projectile: "rocket".into(),
            },
            attack2: Attack::Projectile {
                projectile: "rocket".into(),
            },
            pickup_message1: "PICKED UP: ".into(),
            pickup_message2: "! STAY BACK!".into(),
            fancy_name: "rpg".into(),
        }),
    ]
    .into()
}
