[package]
name = "map_parser"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
faststr = { workspace = true }

[lib]
path = "lib.rs"

[lints]
workspace = true